//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API_NOSA.Models
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    
    public partial class Congviec
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Congviec()
        {
            this.Luucongviecs = new HashSet<Luucongviec>();
            this.NopCVs = new HashSet<NopCV>();
        }
    
        public int id_congviec { get; set; }
        public Nullable<int> id_congty { get; set; }
        public Nullable<int> id_danhmucnganh { get; set; }
        public Nullable<int> id_kynang { get; set; }
        public Nullable<int> id_loaicv { get; set; }
        public Nullable<int> id_loaihinhcv { get; set; }
        public Nullable<int> id_kinhnghiem { get; set; }
        public Nullable<int> id_trinhdo { get; set; }
        public Nullable<int> id_tinh { get; set; }
        public string ten { get; set; }
        public Nullable<int> soluong { get; set; }
        public Nullable<int> luongtoithieu { get; set; }
        public Nullable<int> luongtoida { get; set; }
        public string mota { get; set; }
        public string kinhnghiemchitiet { get; set; }
        public Nullable<System.DateTime> ngaybatdau { get; set; }
        public Nullable<System.DateTime> ngayketthuc { get; set; }
        public Nullable<int> trangthai { get; set; }
        [JsonIgnore]
        public virtual Congty Congty { get; set; }
        [JsonIgnore]
        public virtual Danhmucnganh Danhmucnganh { get; set; }
        [JsonIgnore]
        public virtual Kinhnghiem Kinhnghiem { get; set; }
        [JsonIgnore]
        public virtual Kynang Kynang { get; set; }
        [JsonIgnore]
        public virtual Loaicongviec Loaicongviec { get; set; }
        [JsonIgnore]
        public virtual Loaihinhcongviec Loaihinhcongviec { get; set; }
        [JsonIgnore]
        public virtual Tinhthanh Tinhthanh { get; set; }
        [JsonIgnore]
        public virtual Trinhdohocvan Trinhdohocvan { get; set; }
        [JsonIgnore]
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Luucongviec> Luucongviecs { get; set; }
        [JsonIgnore]
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NopCV> NopCVs { get; set; }
    }
}
