//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API_NOSA.Models
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    
    public partial class Luucongviec
    {
        public int id_luucongviec { get; set; }
        public Nullable<int> id_user { get; set; }
        public Nullable<int> id_congviec { get; set; }
        [JsonIgnore]
        public virtual Congviec Congviec { get; set; }
        [JsonIgnore]
        public virtual User_role User_role { get; set; }
    }
}
