//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API_NOSA.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DBNOSAEntities : DbContext
    {
        public DBNOSAEntities()
            : base("name=DBNOSAEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Congty> Congties { get; set; }
        public virtual DbSet<Congviec> Congviecs { get; set; }
        public virtual DbSet<Danhmucnganh> Danhmucnganhs { get; set; }
        public virtual DbSet<Danhmuctin> Danhmuctins { get; set; }
        public virtual DbSet<Kinhnghiem> Kinhnghiems { get; set; }
        public virtual DbSet<Kynang> Kynangs { get; set; }
        public virtual DbSet<Loaicongviec> Loaicongviecs { get; set; }
        public virtual DbSet<Loaihinhcongviec> Loaihinhcongviecs { get; set; }
        public virtual DbSet<Luucongviec> Luucongviecs { get; set; }
        public virtual DbSet<NopCV> NopCVs { get; set; }
        public virtual DbSet<Tinhthanh> Tinhthanhs { get; set; }
        public virtual DbSet<Tintuc> Tintucs { get; set; }
        public virtual DbSet<Trinhdohocvan> Trinhdohocvans { get; set; }
        public virtual DbSet<User_role> User_role { get; set; }
    }
}
