//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API_NOSA.Models
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    
    public partial class Tintuc
    {
        public int id_tin { get; set; }
        public Nullable<int> id_danhmuctin { get; set; }
        public string tieude { get; set; }
        public string hinhanh { get; set; }
        public string noidung { get; set; }
        public Nullable<System.DateTime> ngaydang { get; set; }
        public string nguoiviet { get; set; }
        [JsonIgnore]

        public virtual Danhmuctin Danhmuctin { get; set; }
    }
}
